.config/tmux: make popuptmux accept session name

diff --git a/private_dot_config/tmux/bin/executable_popuptmux b/private_dot_config/tmux/bin/executable_popuptmux
--- a/private_dot_config/tmux/bin/executable_popuptmux
+++ b/private_dot_config/tmux/bin/executable_popuptmux
@@ -1,9 +1,17 @@
 #! /usr/bin/env bash
 
+session_name=$1
+
+if [ -z "$session_name" ]; then
+    echo "Error: Session name not provided"
+    exit 1
+fi
+
 width=${2:-70%}
 height=${2:-70%}
-if [ "$(tmux display-message -p -F "#{session_name}")" = "popup" ];then
+
+if [ "$(tmux display-message -p -F "#{session_name}")" = "$session_name" ]; then
     tmux detach-client
 else
-    tmux popup -d '#{pane_current_path}' -xC -yC -w$width -h$height  -E "tmux attach -t popup || tmux new -s popup"
+    tmux popup -d '#{pane_current_path}' -xC -yC -w$width -h$height -E "tmux attach -t $session_name || tmux new -s $session_name"
 fi
